packages:
  - "packages/*"
  - "testing/*"

catalogs:
  build:
    "@babel/core": "^7.28.5"
    "@babel/runtime": "^7.28.4"
    "@babel/plugin-transform-runtime": "^7.28.5"
    "@babel/plugin-transform-typescript": "^7.28.5"
    "@babel/eslint-parser": "^7.28.5"
    "typescript": "^5.9.3"
    "vite": "^7.3.0"
  lint:
    "@eslint/js": "^9.29.0"
    "@stylistic/eslint-plugin": "^5.0.0"
    "eslint": "^9.39.1"
    "eslint-config-prettier": "^10.1.5"
    "eslint-plugin-decorator-position": "^6.0.0"
    "eslint-plugin-ember": "^12.7.4"
    "eslint-plugin-import-x": "^4.15.2"
    "eslint-import-resolver-typescript": "^4.4.3"
    "eslint-plugin-json": "^4.0.1"
    "eslint-plugin-n": "^17.20.0"
    "eslint-plugin-prettier": "^5.5.0"
    "eslint-plugin-qunit": "^8.2.5"
    "eslint-plugin-simple-import-sort": "^12.1.1"
    "eslint-plugin-storybook": "^10.0.8"
    "eslint-plugin-unicorn": "^62.0.0"
    "prettier": "^3.6.2"
    "stylelint": "16.26.1"
    "typescript-eslint": "^8.34.0"
