packages:
  - packages/*
  - testing/*
catalogs:
  build:
    "@babel/core": ^7.28.5
    "@babel/runtime": ^7.28.4
    "@babel/plugin-transform-runtime": ^7.28.5
    "@babel/plugin-transform-typescript": ^7.28.5
    "@babel/eslint-parser": ^7.28.5
    "@babel/plugin-proposal-decorators": ^7.28.0
    "@babel/preset-env": 7.28.5
    "@rollup/plugin-babel": "6.1.0"
    babel-plugin-ember-template-compilation: ^3.0.1
    "decorator-transforms": "^2.3.0"
    rollup: 4.55.1
    tsdown: ^0.18.4
    typescript: ^5.9.3
    vite: ^7.3.0
    webpack: 5.104.1
  lint:
    "@eslint/js": ^9.29.0
    "@stylistic/eslint-plugin": ^5.0.0
    eslint: ^9.39.1
    eslint-config-prettier: ^10.1.5
    eslint-plugin-decorator-position: ^6.0.0
    eslint-plugin-ember: ^12.7.4
    eslint-plugin-import-x: ^4.15.2
    eslint-import-resolver-typescript: ^4.4.3
    eslint-plugin-json: ^4.0.1
    eslint-plugin-n: ^17.20.0
    eslint-plugin-prettier: ^5.5.0
    eslint-plugin-qunit: ^8.2.5
    eslint-plugin-simple-import-sort: ^12.1.1
    eslint-plugin-storybook: ^10.0.8
    eslint-plugin-unicorn: ^62.0.0
    prettier: ^3.6.2
    prettier-plugin-ember-template-tag: ^2.0.2
    postcss: 8.5.6
    postcss-each: ^1.1.0
    postcss-lightningcss: ^1.0.1
    postcss-preset-env: ^10.0.0
    stylelint: 16.26.1
    stylelint-config-clean-order: ^8.0.0
    stylelint-config-standard: ^39.0.0
    stylelint-no-unsupported-browser-features: ^8.0.2
    typescript-eslint: ^8.34.0
    "@typescript-eslint/eslint-plugin": ^8.47.0
    "@typescript-eslint/parser": ^8.47.0
  ember:
    "@ember/app-tsconfig": ^2.0.0
    "@ember/library-tsconfig": ^2.0.0
    "@ember/optional-features": "2.3.0"
    "@ember/string": ^4.0.1
    "@ember/test-waiters": ^4.1.0
    "@embroider/addon-dev": 8.2.0
    "@embroider/addon-shim": ^1.8.9
    "@embroider/compat": ^4.1.12
    "@embroider/config-meta-loader": ^1.0.0
    "@embroider/core": ^4.4.2
    "@embroider/macros": ^1.19.6
    "@embroider/router": ^3.0.6
    "@embroider/vite": ^1.5.0
    "@glimmer/tracking": 1.1.2
    "@glimmer/validator": 0.95.0
    "@glimmer/component": "^2.0.0"
    "@glint/ember-tsc": "1.0.9"
    "@glint/template": ^1.7.3
    broccoli-asset-rev: 3.0.0
    # ember-auto-import can't be in a catalog, it doesn't resolve then
    # "ember-auto-import": "2.12.0"
    "ember-cli": "6.9.1"
    ember-cli-app-version: 7.0.0
    "ember-cli-babel": "8.2.0"
    ember-cli-dependency-checker: 3.3.3
    ember-cli-deprecation-workflow: ^4.0.0
    "ember-cli-htmlbars": "^7.0.0"
    ember-cli-inject-live-reload: 2.1.0
    "ember-load-initializers": "^3.0.1"
    ember-cli-sri: 2.1.1
    ember-cli-terser: 4.0.2
    ember-cli-typescript: 5.3.0
    "ember-modifier": "4.2.2"
    "ember-page-title": "9.0.3"
    "ember-resolver": "13.1.1"
    "ember-source": "6.10.0"
    ember-template-imports: 4.4.0
    ember-template-lint: ^7.9.3
    ember-template-lint-plugin-prettier: ^5.0.0
    loader.js: 4.7.0
    tracked-built-ins: ^4.1.0
  types:
    "@types/qunit": ^2.19.13
    "@types/rsvp": ^4.0.9
  test:
    "@ember/test-helpers": "5.4.1"
    ember-qunit: ^9.0.4
    qunit: ^2.24.3
    qunit-dom: ^3.5.0
    testem: ^3.17.0
    vitest: ^4.0.16
  lib:
    "@storybook/types": "^8.6.14"
    "globals": "^16.5.0"
    storybook: ^10.1.10
