name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  # install_dependencies:
  #   name: Install Dependencies
  #   timeout-minutes: 5
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: volta-cli/action@v3
  #     - name: Cache pnpm modules
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.pnpm-store
  #         key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
  #         restore-keys: ${{ runner.os }}-
  #     - uses: pnpm/action-setup@v2.2.2
  #       with:
  #         version: latest
  #     - name: Install Dependencies
  #       run: pnpm install

  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    # needs:
    #   - install_dependencies

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      - name: Install
        run: pnpm install
      - name: Lint
        run: pnpm run -r --parallel --aggregate-output lint
