name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-js:
    name: 'Lint: JS'
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: wyvox/action@v1
      - name: Lint
        run: pnpm run -r --parallel --aggregate-output lint:js

  lint-types:
    name: 'Lint: Types'
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: wyvox/action@v1
      - name: Lint
        run: pnpm run -r --parallel --aggregate-output lint:types

  lint-hbs:
    name: 'Lint: Handlebars'
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: wyvox/action@v1
      - name: Lint
        run: pnpm run -r --parallel --aggregate-output lint:hbs

  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: wyvox/action@v1
      - name: Run Tests
        run: pnpm --filter ember-app run test:ember
